#!/bin/bash

read -p "This script was made by a noob. Make sure you've backup any changes before proceeding. Would you like to continue? (y/n)" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	echo "Copying Assets..."
	cp ./site.css ~/local_html/ct310/m2/assets/css/
	chmod 755 ~/local_html/ct310/m2/assets/css/site.css
	echo "Done"

	echo "Copying Controller Files..."
	cp ./m2.php ~/fuel/app/classes/controller/
	chmod 755 ~/fuel/app/classes/controller/m2.php
	echo "Done"

	echo "Copying Model Files..."
	cp ./report.php ~/fuel/app/classes/model/
	chmod 755 ~/fuel/app/classes/model/report.php
	echo "Done"

	echo "Copying View Files..."
	cp ./about.php ~/fuel/app/views/m2/
	cp ./index.php ~/fuel/app/views/m2/
	cp ./more_information.php ~/fuel/app/views/m2/
	chmod 755 ~/fuel/app/views/m2/about.php ~/fuel/app/views/m2/index.php ~/fuel/app/views/m2/more_information.php
	echo "Done"

	echo "Copying Resource Files..."
	cp default.csv ~/local_html/ct310/m2/
	chmod 755 ~/local_html/ct310/m2/default.csv
	echo "Done"
fi
